package project4;

public enum GameEvent {
    CAPTURED_SMALL,
    PARTIALLY_CAPTURED_SMALL,
    AVOIDED_SMALL,
    CAPTURED_BIG,
    PARTIALLY_CAPTURED_BIG,
    AVOIDED_BIG,
    NOTHING,
    GAME_OVER
}
